# Generated by Django 3.0.5 on 2020-04-26 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200426_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='orderdate',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='totcost',
            field=models.IntegerField(),
        ),
    ]
